apiVersion: v1
kind: ConfigMap
metadata:
  name: self-information-app-config
data:
  application.properties: |-
    # https://spring.io/guides/topicals/spring-on-kubernetes
    server.shutdown=graceful
    management.endpoints.web.exposure.include=*
