apiVersion: v1
kind: Service
metadata:
  name: self-information-service
  labels:
    app: self-information-app
spec:
  type: NodePort
  ports:
    - port: 8080
      name: http
      targetPort: 8080
    - port: 1044
      name: debug
      targetPort: 1044
  selector:
    app: self-information-app
